export enum SQLType {
  DML_SELECT = 'DML_SELECT',
  DML_INSERT = 'DML_INSERT',
  DML_UPDATE = 'DML_UPDATE',
  DML_DELETE = 'DML_DELETE',
  DDL_TABLE = 'DDL_TABLE',
  DDL_DATABASE = 'DDL_DATABASE',
  ZOTHER_FUNCTIONS = 'ZOTHER_FUNCTIONS'
}
